# Generated by Django 4.1.7 on 2023-04-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
            ],
        ),
    ]
