# Generated by Django 4.1.7 on 2023-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('photo1', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı1')),
                ('photo2', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı2')),
                ('photo3', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı3')),
                ('photo4', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı4')),
                ('photo5', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı5')),
                ('photo6', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı6')),
                ('photo7', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı7')),
                ('photo8', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı8')),
                ('photo9', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı9')),
                ('photo10', models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı10')),
                ('homepage', models.BooleanField(default=False, verbose_name='Anasayfada Gözüksün')),
                ('category', models.ManyToManyField(to='main.category')),
            ],
        ),
    ]
