# Generated by Django 4.1.7 on 2023-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo9',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ürün Fotoğrafı'),
        ),
    ]
