# Generated by Django 4.1.7 on 2023-06-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_photo1_remove_product_photo10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='s1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_1', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_10', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_2', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_3', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_4', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_5', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_6', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_7', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_8', to='main.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='s9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_kategori_9', to='main.subcategory'),
        ),
    ]
