# Generated by Django 4.1.7 on 2023-06-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s10',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s5',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s6',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s7',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s8',
        ),
        migrations.RemoveField(
            model_name='category',
            name='s9',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ManyToManyField(null=True, related_name='alt_kategori', to='main.subcategory'),
        ),
    ]
